### PR TITLE
Use modern APIs and proper wikitext parsing

### PR DESCRIPTION
**Pull request by legoktm**
- Use format=json&formatversion=2 for all API queries
- Use python-requests instead of shelling out to wget
- Move all code into functions
- Use mwparserfromhell for all wikitext parsing instead of regex
- No screenscraping. Use image metadata instead
- Don't bother writing to files to communicate between functions

### CODE REVIEW

**Comment by legoktm** [comment]
I tested it on tool labs and received: http://fpaste.org/300162/53756144/raw/

**Comment by ricordisamoa** [comment]
## Hooray!

Do you consider formatversion=2 to be stable enough?

**Comment by legoktm** [comment]
Yeah (partially because I review most of them ;-)). And if breaking changes happen, they're announced on the mediawiki-api-announce list.

**Comment by Steinsplitter** [comment]
https://commons.wikimedia.org/w/index.php?title=Main_Page&diff=181752362&oldid=181637738

Thanks lego! :-)

**Comment by ricordisamoa** [comment]
Also if it were to support Python 3 only, `urllib.request` might render `requests` unnecessary?

**Comment by legoktm** [comment]
Maybe, but I find the `requests` API much easier to use with direct functions like `requests.get()`, `Response.json()` and `Response.raise_for_status()`.

**Comment by ricordisamoa** [comment]
> Maybe, but I find the requests API much easier to use with direct functions like requests.get(), Response.json() and Response.raise_for_status().

Awesome as always, thank you.

**Pull request merged**
